
version: 2.1

jobs:
  deploy-to-head-node:
    docker:
      - image: circleci/python:3.9  # Python image with necessary tools
    environment:
      SSH_USER: "ubuntu"
      SSH_HOST: "154.114.57.80"
      PLAYBOOK_FILE: "install_hpl.yml"   # Ansible playbook file
      INVENTORY_FILE: "inventory.yml"     # Ansible inventory file
    steps:
      - checkout

      # Add SSH keys managed by CircleCI
      - add_ssh_keys:
          fingerprints:
            - "SHA256:SHIa6LYWWEELTDhxKtNh5rv53Zx+8hj4y/kGipCJ0Yg"

      # Install Dependencies
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-openstackclient openssh-client ansible

      # Setup SSH
      - run:
          name: Setup SSH
          command: |
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            ssh-keyscan -H ${SSH_HOST} >> ~/.ssh/known_hosts

      # Transfer Ansible Directory to Head Node
      - run:
          name: Transfer Ansible Directory
          command: |
            scp -r ./ansible ${SSH_USER}@${SSH_HOST}:~/ || { echo "SCP failed"; exit 1; }

      # Deploy and Run Ansible Playbook
      - run:
          name: Deploy and Run Ansible Playbook
          command: |
            ssh ${SSH_USER}@${SSH_HOST} "cd ~/ansible && ansible-playbook ${PLAYBOOK_FILE} -i ${INVENTORY_FILE}" || { echo "Ansible playbook failed"; exit 1; }

workflows:
  deploy-workflow:
    jobs:
      - deploy-to-head-node

