version: 2.1

jobs:
  deploy:
    docker:
      - image: hashicorp/terraform:latest  # Official Terraform Docker image
    steps:
      - checkout  # Checks out your repository

      # Initialize Terraform
      - run:
          name: Terraform Init
          command: terraform init

      # Apply Terraform Configuration
      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve

workflows:
  deploy_workflow:
    jobs:
      - deploy
