# roles/install_hpl/tasks/main.yml
---
- name: Create HPL.dat file with specific content
  copy:
    dest: "{{ ansible_env.HOME }}/hpl/bin/compile_BLAS_MPI/HPL.dat"
    content: |
      HPLinpack benchmark input file
      Innovative Computing Laboratory, University of Tennessee
      HPL.out      output file name (if any)
      6            device out (6=stdout,7=stderr,file)
      1            # of problems sizes (N)
      21976         Ns
      1            # of NBs
      164           NBs
      0            PMAP process mapping (0=Row-,1=Column-major)
      1            # of process grids (P x Q)
      4            Ps
      4            Qs
      16.0         threshold
      1            # of panel fact
      2            PFACTs (0=left, 1=Crout, 2=Right)
      1            # of recursive stopping criterium
      4            NBMINs (>= 1)
      1            # of panels in recursion
      2            NDIVs
      1            # of recursive panel fact.
      1            RFACTs (0=left, 1=Crout, 2=Right)
      1            # of broadcast
      1            BCASTs (0=1rg,1=1rM,2=2rg,3=2rM,4=Lng,5=LnM)
      1            # of lookahead depth
      1            DEPTHs (>=0)
      2            SWAP (0=bin-exch,1=long,2=mix)
      64           swapping threshold
      0            L1 in (0=transposed,1=no-transposed) form
      0            U  in (0=transposed,1=no-transposed) form
      1            Equilibration (0=no,1=yes)
      8            memory alignment in double (> 0)

- name: Create a hostfile for mpirun
  copy:
    dest: "{{ ansible_env.HOME }}/hpl/bin/compile_BLAS_MPI/hostfile"
    content: |
      # Headnode included in the hostfile with its cores
      {{ ansible_host }} slots= 2

      # Compute nodes included dynamically
      {% for host in groups['compute'] %}
      {{ hostvars[host]['ansible_host'] }} slots= 8
      {% endfor %}

- name: Execute HPL benchmark across nodes
  shell: |
    export PATH=~/opt/openmpi/bin:~/opt/openblas:$PATH
    export LD_LIBRARY_PATH=~/opt/openmpi/lib:~/opt/openblas/lib:$LD_LIBRARY_PATH
    export MPI_HOME=~/opt/openmpi
    mpirun -np 16 --hostfile ~/hpl/bin/compile_BLAS_MPI/hostfile --prefix ~/opt/openmpi ~/hpl/bin/compile_BLAS_MPI/xhpl
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}/hpl/bin/compile_BLAS_MPI"
  register: hpl_result

- name: Display HPL output
  debug:
    var: hpl_result.stdout

- name: Save HPL result to a file
  copy:
    dest: "{{ ansible_env.HOME }}/hpl/bin/compile_BLAS_MPI/hpl_output.txt"
    content: "{{ hpl_result.stdout }}"
  delegate_to: localhost
